name: Upload coverage reports to Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup/
        with:
          python-version: "3.10"
      - name: Run tests and collect coverage
        run: pytest --cov=build123d
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
