name: pylint

on: [push, pull_request]
jobs:
  lint:
    strategy:
      matrix:
        python-version: [ "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: lint
        run: pylint --rcfile=.pylintrc --fail-under=9.5 src/build123d
