name: Run type checker

on: [push, pull_request]
jobs:
  typecheck:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          # "3.11",
          "3.12"
          ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: typecheck
        run: |
          mypy --config-file mypy.ini src/build123d
