name: tests

on: [push, pull_request, workflow_dispatch]
jobs:

  tests_x86_64:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          # "3.11",
          "3.12",
          ]
        os: [macos-13, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/
        with:
          python-version: ${{ matrix.python-version }}
      - name: test
        run: |
          python -m pytest

  tests_arm64:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          #"3.11",
          #"3.12"
          ]
        os: [macos-14]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-macos-arm64/
        with:
          python-version: ${{ matrix.python-version }}
      - name: test
        run: |
          python -m pytest
